app = "meta-service-sgm-dev"

primary_region = "gru"

[env]
  PORT = "8080"
  RAILS_ENV = "development"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

[experimental]
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]
